### ISSUE TITLE
Can't install this package according the dependence conflicts for speechmetrics packages

### ISSUE THREAD

**Issue by Corleno** [XiaoyuBIE1994/DVAE#2]
I find that I cannot build the image because of the issue in https://github.com/aliutkus/speechmetrics/issues/20.
I have made a temporary workaround by forking your repo and adjusting your dvae.def and setup.py to install the speechmetric from https://github.com/KnurpsBram/speechmetrics here. https://github.com/Corleno/DVAE-speech. Hope this will benefit more people who want to use your package.

**Comment by XiaoyuBIE1994** [comment]
Hi sorry for my late response, I'll remove the speechmetrics package in the following version, might in August.
