### ISSUE TITLE
Requesting the original RVAE (causal) implementation code

### ISSUE THREAD

**Issue by rppravin** [XiaoyuBIE1994/DVAE#4]
Thanks for the great ICASSP 2021 tutorial.

It mentioned (slide 103/133) that the original RVAE code gives better results than this repository. Could you please share the code location? Specifically, looking for the causal implementation.

Thank you,
Pravin

**Comment by XiaoyuBIE1994** [comment]
Hello Pravin, 

Thanks for your interest. We use similar model architecture for fair comparison in the DVAE review paper. For a better performed RVAE model, you could find in our repo for speech enhancement [https://github.com/XiaoyuBIE1994/DVAE_SE/tree/master/trained_models/wsj_rvae](https://github.com/XiaoyuBIE1994/DVAE_SE/tree/master/trained_models/wsj_rvae)

**Comment by rppravin** [comment]
Thank you for the reply.
